### PR TITLE
Card height and hover changes

### PR DESCRIPTION
**Pull request by Jaimin25**
- Changed the cards' height to 450px; they all look the same.
- Added a hover effect to the cards

Please let me know if any more changes needed.

https://github.com/CareerDevelopmentHub/SocialHub/assets/65119631/029f5c41-8844-4867-8268-a5a0570f455a

### CODE REVIEW

**Comment by suhani1804** [comment]
@Jaimin25 I expect gradient hover effect on cards that will look attractive and decent.

**Comment by Jaimin25** [comment]
@suhani1804 sure, can the gradient color be similar to the bg color of the website or something different?

**Comment by Jaimin25** [comment]
> Without glow effect

https://github.com/CareerDevelopmentHub/SocialHub/assets/65119631/9bedb64c-087c-47c3-900a-77133457c13c



> With glow effect

https://github.com/CareerDevelopmentHub/SocialHub/assets/65119631/6195c256-161b-4862-954f-01a71abd3c1f


Which is looking better

**Comment by suhani1804** [comment]
go with the second one

**Comment by Jaimin25** [comment]
@suhani1804 done, please review it

**Pull request merged**
