### PR TITLE
 Added My Profile And Dark theme to website 

### PR DESCRIPTION
**Pull request by ankit071105**

### CODE REVIEW

**Comment by suhani1804** [comment]
Your styles.css is conflicting in the branch. Please change it

**Comment by ankit071105** [comment]
resolve the conflicts

**Comment by suhani1804** [comment]
> resolve the conflicts

Again your styles.css and index.html is conflicting in the branch. Please change it

**Comment by ankit071105** [comment]
> > resolve the conflicts
> 
> Again your styles.css and index.html is conflicting in the branch. Please change it

now i think it has been resolve you can check it once

**Comment by suhani1804** [comment]
> > > resolve the conflicts
> > 
> > 
> > Again your styles.css and index.html is conflicting in the branch. Please change it
> 


> now i think it has been resolve you can check it once

Screenshot 2023-10-16 114109

please check

**Pull request closed without merging**
