### PR TITLE
Added my own social and changed footer anchors

### PR DESCRIPTION
**Pull request by DAddy-is-CODing2**

### CODE REVIEW

**Comment by suhani1804** [comment]
Please review your code again. It's conflicting

**Comment by DAddy-is-CODing2** [comment]
done

**Comment by suhani1804** [comment]
Screenshot 2023-10-20 093201

Please fix it

**Comment by suhani1804** [comment]
> is it fixed now?

No

**Comment by DAddy-is-CODing2** [comment]
Screenshot (55)

**Comment by suhani1804** [comment]
@DAddy-is-CODing2 Please don't include code files in the asset folder. Fix this

**Comment by DAddy-is-CODing2** [comment]
i changed it

**Comment by DAddy-is-CODing2** [comment]
thank you

**Pull request merged**
