### PR TITLE
Created and added About me page

### PR DESCRIPTION
**Pull request by Pratik-k-sahoo**
Created and added ABOUT ME PAGE in home page and updated the link of the card.
Designed a UI of of comic theme and created cards for socials. #hacktoberfest #octohub

### CODE REVIEW

**Comment by Pratik-k-sahoo** [comment]
Created and added ABOUT ME PAGE in home page and updated the link of the card.
Designed a UI of of comic theme and created cards for socials.

**Comment by Pratik-k-sahoo** [comment]
Created and added ABOUT ME PAGE in home page and updated the link of the card.
Designed a UI of of comic theme and created cards for socials.

**Comment by suhani1804** [comment]
> Created and added ABOUT ME PAGE in home page and updated the link of the card. Designed a UI of of comic theme and created cards for socials. #hacktoberfest #octohub

Try to add your own image instead of the demo image

**Comment by Pratik-k-sahoo** [comment]
I did but as you have merged the PR#10 I think it occurs. And the image you are referring is that the home page index.html image?

**Comment by Pratik-k-sahoo** [comment]
> > Created and added ABOUT ME PAGE in home page and updated the link of the card. Designed a UI of of comic theme and created cards for socials. #hacktoberfest #octohub
> 
> Please review the index.html page. you have added conflicting code 
> Try to add your own image instead of the demo image

I did but as you have merged the PR#10 I think it occurs. And the image you are referring is that the home page index.html image?

**Pull request closed without merging**
