### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by Jaimin25**
Worked on #1 

**Made navbar blury**
> image

**Width changes to about and contact div**
> image
> image

**Changed bg radient**
> image

**Changes to bg effect when hover card**
> image

### CODE REVIEW

**Comment by Jaimin25** [comment]
When clicking the SocialHub logo in the navbar, it will send the user back to the home page. I will try to make UI look more attractive :)

**Comment by suhani1804** [comment]
awesome! Can you please review your index.html and contact.css file.

**Comment by Jaimin25** [comment]
@suhani1804 please review the resolved conflicts.

**Comment by suhani1804** [comment]
Screenshot 2023-10-20 103337

Please fix it in about page

**Comment by Jaimin25** [comment]
That was a problem in contact page also, fixed it, hope everything's looking good now 😅

**Comment by suhani1804** [comment]
> That was a problem in contact page also, fixed it, hope everything's looking good now 😅

yes it's better. Thank you for contributing.

**Pull request merged**
